/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/admin-mst/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['adminMst.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Store admin mst */
    post: operations['adminMst.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update admin mst */
    put: operations['adminMst.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete admin mst */
    post: operations['adminMst.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/audit-log/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit log, newest first by default (read-only, ADR-0006) */
    get: operations['auditLog.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in: starts the session. Call `GET /api/sanctum/csrf-cookie` first */
    post: operations['credential.login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out: ends the session (also succeeds without one) */
    post: operations['credential.logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in admin */
    get: operations['credential.me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sanctum/csrf-cookie': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return an empty response simply to trigger the storage of the CSRF cookie in the browser */
    get: operations['sanctum.csrf-cookie'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/dashboard/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Skill Ledger counts for the dashboard */
    get: operations['dashboard.summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/evidence/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['evidence.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/evidence/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an evidence link for one or more skills */
    post: operations['evidence.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/evidence/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update an evidence link (imported rows: only type and is_public) */
    put: operations['evidence.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/evidence/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['evidence.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/evidence/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sync the complete list of published Obsidian notes (idempotent; `dry_run` only counts)
     * @description Called by the importer CLI with an API token that has the `evidence:import` ability, or by the owner's session.
     */
    post: operations['evidenceImport.import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/learning-goal/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['learningGoal.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/learning-goal/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an open goal; the target must be above the current level */
    post: operations['learningGoal.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/learning-goal/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a goal (status open or dropped; achieved goals: date and note only) */
    put: operations['learningGoal.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/learning-goal/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['learningGoal.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/skills': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public skills, by name */
    get: operations['publicSkill.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/skills/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One public skill with its level history dates and public evidence; private or missing → 404 */
    get: operations['publicSkill.show'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search skills, goals and evidence (accents and case ignored; typo fallback when nothing matches) */
    get: operations['search.search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['skill.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a skill with its first level entry */
    post: operations['skill.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a skill (its level changes through skill-level/store) */
    put: operations['skill.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['skill.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill-level/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['skillLevel.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skill-level/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record a level change; open goals reached by it become achieved */
    post: operations['skillLevel.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tag/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tag.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tag/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['tag.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tag/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['tag.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tag/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['tag.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminMstResource */
    AdminMstResource: {
      id: number;
      email: string;
      user_name: string;
      first_name: string;
      last_name: string;
      address: string;
      phone_number: string;
      birth: string | null;
      gender: number;
      status: number;
      is_active: boolean;
      role: string;
      avatar: string;
      is_delete: boolean;
      updated_at: string;
    };
    /**
     * AdminRole
     * @description The two admin roles (ADR-0005): an owner may change data, a viewer may only read it.
     * @enum {string}
     */
    AdminRole: 'owner' | 'viewer';
    /**
     * AdminStatus
     * @enum {integer}
     */
    AdminStatus: 0 | 1 | 2 | 3;
    /** ApiError */
    ApiError: {
      data: null;
      error: {
        status: boolean;
        code: number;
        messages:
          | string
          | {
              [key: string]: string[];
            };
      };
    };
    /**
     * AuditEvent
     * @description What an audit_log row records (ADR-0006).
     * @enum {string}
     */
    AuditEvent: 'created' | 'updated' | 'deleted' | 'logged_in' | 'logged_out' | 'login_failed';
    /** AuditLogResource */
    AuditLogResource: {
      id: number;
      auditable_type: string;
      auditable_id: number | null;
      event: string;
      old_values: {
        [key: string]: unknown;
      } | null;
      new_values: {
        [key: string]: unknown;
      } | null;
      admin_mst_id: number | null;
      actor_user_name: string | null;
      ip_address: string | null;
      /** @description Full timestamp (ISO 8601): the time of day matters in an audit trail */
      created_at: string;
    };
    /** DeleteAdminMstRequest */
    DeleteAdminMstRequest: {
      ids: number[];
    };
    /** DeleteEvidenceRequest */
    DeleteEvidenceRequest: {
      ids: number[];
    };
    /** DeleteLearningGoalRequest */
    DeleteLearningGoalRequest: {
      ids: number[];
    };
    /** DeleteSkillRequest */
    DeleteSkillRequest: {
      ids: number[];
    };
    /** DeleteTagRequest */
    DeleteTagRequest: {
      ids: number[];
    };
    /** EvidenceResource */
    EvidenceResource: {
      id: number;
      type: components['schemas']['EvidenceType'];
      title: string;
      url: string;
      occurred_on: string;
      summary: string | null;
      is_public: boolean;
      source: components['schemas']['EvidenceSource'];
      unpublished_at: string | null;
      skills?: {
        id: number;
        name: string;
      }[];
      tags?: components['schemas']['TagResource'][];
      created_at: string | null;
      updated_at: string | null;
    };
    /**
     * EvidenceSource
     * @description Who owns an evidence row: typed in the admin, or synced from the Obsidian vault (RFC-002 §4.5).
     * @enum {string}
     */
    EvidenceSource: 'manual' | 'obsidian';
    /**
     * EvidenceType
     * @description What a piece of evidence links to (REQ-002 Q3).
     * @enum {string}
     */
    EvidenceType: 'pr' | 'adr' | 'incident' | 'note' | 'other';
    /**
     * Gender
     * @enum {integer}
     */
    Gender: 1 | 2 | 3;
    /**
     * GoalStatus
     * @description Learning goal lifecycle (REQ-002 Q2): open goals become achieved when the skill reaches the target level.
     * @enum {string}
     */
    GoalStatus: 'open' | 'achieved' | 'dropped';
    /**
     * ImportEvidenceRequest
     * @description The complete list of published Obsidian notes (RFC-002 §4.5, ADR-0010 importer contract).
     *     Skills and tags are names, not ids: unknown skills are reported, missing tags are created.
     */
    ImportEvidenceRequest: {
      /** @description An empty list is valid: the vault has no published note left, so every imported row is hidden */
      notes: {
        external_key: string;
        title: string;
        /** Format: uri */
        url: string;
        /** Format: date */
        occurred_on: string;
        summary?: string | null;
        tags?: string[];
        skills?: string[];
      }[];
      dry_run?: boolean;
    };
    /**
     * IsActive
     * @enum {integer}
     */
    IsActive: 0 | 1;
    /**
     * IsDelete
     * @enum {integer}
     */
    IsDelete: 0 | 1;
    /** LearningGoalResource */
    LearningGoalResource: {
      id: number;
      skill: {
        id: number;
        name: string;
        current_level: number;
      };
      target_level: components['schemas']['SkillLevel'];
      /** @enum {string} */
      target_level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
      target_date: string | null;
      status: components['schemas']['GoalStatus'];
      achieved_on: string | null;
      note: string | null;
      created_at: string | null;
      updated_at: string | null;
    };
    /** LoginRequest */
    LoginRequest: {
      user_name: string;
      password: string;
    };
    /** PaginationLinks */
    PaginationLinks: {
      first: string | null;
      last: string | null;
      prev: string | null;
      next: string | null;
    };
    /** PaginationMeta */
    PaginationMeta: {
      current_page: number;
      from: number | null;
      last_page: number;
      links: {
        url: string | null;
        label: string;
        page: number | null;
        active: boolean;
      }[];
      path: string;
      per_page: number;
      to: number | null;
      total: number;
    };
    /** PublicSkillDetailResource */
    PublicSkillDetailResource: {
      name: string;
      slug: string;
      category: string;
      current_level: number;
      /** @enum {string} */
      current_level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
      tags: string[];
      description: string | null;
      history: {
        level: number;
        /** @enum {string} */
        level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
        changed_on: string;
      }[];
      evidence: {
        type: components['schemas']['EvidenceType'];
        title: string;
        url: string;
        occurred_on: string;
        summary: string | null;
      }[];
    };
    /** PublicSkillResource */
    PublicSkillResource: {
      name: string;
      slug: string;
      category: string;
      current_level: number;
      /** @enum {string} */
      current_level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
      tags: string[];
    };
    /**
     * SearchMatch
     * @description Which search mode answered (ADR-0009): the UI shows "did you mean" wording for fuzzy results.
     * @enum {string}
     */
    SearchMatch: 'exact' | 'fuzzy';
    /**
     * SkillLevel
     * @description The fixed four-step skill scale (REQ-002 Q1).
     * @enum {integer}
     */
    SkillLevel: 1 | 2 | 3 | 4;
    /** SkillLevelResource */
    SkillLevelResource: {
      id: number;
      skill_id: number;
      level: number;
      /** @enum {string} */
      level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
      reason: string | null;
      changed_on: string;
      recorded_by_user_name: string | null;
      created_at: string;
    };
    /** SkillResource */
    SkillResource: {
      id: number;
      name: string;
      slug: string;
      category: string;
      description: string | null;
      is_public: boolean;
      current_level: number;
      /** @enum {string} */
      current_level_label: 'Learning' | 'Can use with help' | 'Independent' | 'Can teach others';
      tags?: components['schemas']['TagResource'][];
      created_at: string | null;
      updated_at: string | null;
    };
    /**
     * StatusEnum
     * @enum {integer}
     */
    StatusEnum: 0 | 1 | 2;
    /** StoreAdminMstRequest */
    StoreAdminMstRequest: {
      /** Format: email */
      email: string;
      user_name: string;
      password: string;
      first_name: string;
      last_name: string;
      address?: string | null;
      phone_number?: string | null;
      birth?: string | null;
      gender: components['schemas']['Gender'];
      status: components['schemas']['AdminStatus'];
      is_active: components['schemas']['IsActive'];
      role?: components['schemas']['AdminRole'];
      avatar?: string | null;
      is_delete: components['schemas']['IsDelete'];
    };
    /**
     * StoreEvidenceRequest
     * @description Evidence is a link only (ADR-0007). `source`, `external_key` and `unpublished_at` belong
     *     to the importer (RFC-002 §4.5) and are not accepted here.
     */
    StoreEvidenceRequest: {
      type: components['schemas']['EvidenceType'];
      title: string;
      /**
       * Format: uri
       * @description http(s) only: blocks javascript: and data: links on the public page (REQ-002 US-2)
       */
      url: string;
      /** Format: date */
      occurred_on: string;
      summary?: string | null;
      is_public?: boolean;
      skill_ids: number[];
      tag_ids?: number[];
    };
    /**
     * StoreLearningGoalRequest
     * @description A new goal is always open; the target must be above the skill's current level (LearningGoalService).
     */
    StoreLearningGoalRequest: {
      skill_id: number;
      target_level: components['schemas']['SkillLevel'];
      /** Format: date */
      target_date?: string | null;
      note?: string | null;
    };
    /** StoreSkillLevelRequest */
    StoreSkillLevelRequest: {
      skill_id: number;
      level: components['schemas']['SkillLevel'];
      /** Format: date */
      changed_on?: string;
      reason?: string | null;
    };
    /**
     * StoreSkillRequest
     * @description A skill is created together with its first level entry (RFC-002 §4.2).
     */
    StoreSkillRequest: {
      name: string;
      category: string;
      description?: string | null;
      is_public?: boolean;
      tag_ids?: number[];
      level: components['schemas']['SkillLevel'];
      /** Format: date */
      changed_on?: string;
      reason?: string | null;
    };
    /** StoreTagRequest */
    StoreTagRequest: {
      name: string;
    };
    /** TagResource */
    TagResource: {
      id: number;
      name: string;
    };
    /** UpdateAdminMstRequest */
    UpdateAdminMstRequest: {
      id: number;
      /** Format: email */
      email: string;
      user_name: string;
      password?: string | null;
      first_name: string;
      last_name: string;
      address?: string | null;
      phone_number?: string | null;
      birth?: string | null;
      gender: components['schemas']['Gender'];
      status: components['schemas']['AdminStatus'];
      is_active: components['schemas']['IsActive'];
      role?: components['schemas']['AdminRole'];
      avatar?: string | null;
      is_delete?: components['schemas']['IsDelete'] | null;
    };
    /**
     * UpdateEvidenceRequest
     * @description Same fields as store, each optional. Imported rows accept only `type` and `is_public`
     *     (EvidenceService::update).
     */
    UpdateEvidenceRequest: {
      type?: components['schemas']['EvidenceType'];
      title?: string;
      /**
       * Format: uri
       * @description http(s) only: blocks javascript: and data: links on the public page (REQ-002 US-2)
       */
      url?: string;
      /** Format: date */
      occurred_on?: string;
      summary?: string | null;
      is_public?: boolean;
      skill_ids?: number[];
      tag_ids?: number[];
    };
    /**
     * UpdateLearningGoalRequest
     * @description The skill of a goal is fixed. `achieved` is set only by a level change (REQ-002 US-6),
     *     so the status can be switched between open and dropped only.
     */
    UpdateLearningGoalRequest: {
      target_level?: components['schemas']['SkillLevel'];
      /** Format: date */
      target_date?: string | null;
      /**
       * @description Learning goal lifecycle (REQ-002 Q2): open goals become achieved when the skill reaches the target level.
       * @enum {string}
       */
      status?: 'open' | 'dropped';
      note?: string | null;
    };
    /**
     * UpdateSkillRequest
     * @description No level field: levels change only through skill-level/store, so the history stays complete.
     *     The slug is not editable either; public URLs stay stable across renames.
     */
    UpdateSkillRequest: {
      name?: string;
      category?: string;
      description?: string | null;
      is_public?: boolean;
      tag_ids?: number[];
    };
    /** UpdateTagRequest */
    UpdateTagRequest: {
      name: string;
    };
  };
  responses: {
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiError'];
      };
    };
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiError'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'adminMst.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        email?: string | null;
        user_name?: string | null;
        first_name?: string | null;
        last_name?: string | null;
        address?: string | null;
        phone_number?: string | null;
        birth?: string | null;
        gender?: components['schemas']['Gender'] | null;
        status?: components['schemas']['StatusEnum'] | null;
        is_active?: components['schemas']['IsActive'] | null;
        role?: components['schemas']['AdminRole'] | null;
        avatar?: string | null;
        is_delete?: components['schemas']['IsDelete'] | null;
        from_date?: string | null;
        to_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `AdminMstResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['AdminMstResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'auditLog.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        auditable_type?: string | null;
        auditable_id?: number | null;
        event?: components['schemas']['AuditEvent'] | null;
        admin_mst_id?: number | null;
        from_date?: string | null;
        to_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `AuditLogResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['AuditLogResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'credential.login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: number;
              email: string;
              user_name: string;
              first_name: string;
              last_name: string;
              address: string;
              phone_number: string;
              birth: string | null;
              gender: number;
              status: number;
              is_active: boolean;
              role: string;
              avatar: string;
              is_delete: boolean;
              updated_at: string;
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'credential.logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
    };
  };
  'credential.me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              id: number;
              email: string;
              user_name: string;
              first_name: string;
              last_name: string;
              address: string;
              phone_number: string;
              birth: string | null;
              gender: number;
              status: number;
              is_active: boolean;
              role: string;
              avatar: string;
              is_delete: boolean;
              updated_at: string;
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'sanctum.csrf-cookie': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description No content
       *
       *     No content
       */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown[];
        };
      };
    };
  };
  'dashboard.summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              skills: number;
              public_skills: number;
              evidence: number;
              public_evidence: number;
              open_goals: number;
              levels: {
                level: number;
                level_label: string;
                count: number;
              }[];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'evidence.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        title?: string | null;
        type?: components['schemas']['EvidenceType'] | null;
        source?: components['schemas']['EvidenceSource'] | null;
        is_public?: boolean | null;
        skill_id?: number | null;
        tag_id?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `EvidenceResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['EvidenceResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'evidence.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreEvidenceRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'evidence.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateEvidenceRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'evidence.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteEvidenceRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'evidenceImport.import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ImportEvidenceRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              created: number;
              updated: number;
              unchanged: number;
              hidden: number;
              unknown_skills: string[];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'learningGoal.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        skill_id?: number | null;
        status?: components['schemas']['GoalStatus'] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `LearningGoalResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['LearningGoalResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'learningGoal.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreLearningGoalRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'learningGoal.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateLearningGoalRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'learningGoal.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteLearningGoalRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'publicSkill.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `PublicSkillResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['PublicSkillResource'][];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'publicSkill.show': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `PublicSkillDetailResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['PublicSkillDetailResource'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  'search.search': {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              match: components['schemas']['SearchMatch'];
              skills: {
                id: number;
                title: string;
                snippet: string | null;
              }[];
              goals: {
                id: number;
                title: string;
                snippet: string | null;
              }[];
              evidence: {
                id: number;
                title: string;
                snippet: string | null;
              }[];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skill.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        name?: string | null;
        category?: string | null;
        is_public?: boolean | null;
        current_level?: components['schemas']['SkillLevel'] | null;
        tag_id?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `SkillResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['SkillResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skill.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreSkillRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skill.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateSkillRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skill.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteSkillRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skillLevel.list': {
    parameters: {
      query: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        skill_id: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `SkillLevelResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['SkillLevelResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'skillLevel.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreSkillLevelRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'tag.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        name?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `TagResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              data: components['schemas']['TagResource'][];
              links: components['schemas']['PaginationLinks'];
              meta: components['schemas']['PaginationMeta'];
            };
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'tag.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreTagRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'tag.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTagRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: number;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'tag.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteTagRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: null;
            error: {
              status: boolean;
              code: number;
              messages: null;
            };
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
}
