/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/admin-mst/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['adminMst.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Store admin mst */
    post: operations['adminMst.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/update/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update admin mst */
    put: operations['adminMst.update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/admin-mst/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete admin mst */
    post: operations['adminMst.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/audit-log/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit log, newest first by default (read-only, ADR-0006) */
    get: operations['auditLog.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in: starts the session. Call `GET /api/sanctum/csrf-cookie` first */
    post: operations['credential.login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out: ends the session (also succeeds without one) */
    post: operations['credential.logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/credential/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in admin */
    get: operations['credential.me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sanctum/csrf-cookie': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return an empty response simply to trigger the storage of the CSRF cookie in the browser */
    get: operations['sanctum.csrf-cookie'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminMstResource */
    AdminMstResource: {
      id: number;
      email: string;
      user_name: string;
      first_name: string;
      last_name: string;
      address: string;
      phone_number: string;
      birth: string | null;
      gender: number;
      status: number;
      is_active: boolean;
      role: string;
      avatar: string;
      is_delete: boolean;
      updated_at: string;
    };
    /**
     * AdminRole
     * @description The two admin roles (ADR-0005): an owner may change data, a viewer may only read it.
     * @enum {string}
     */
    AdminRole: 'owner' | 'viewer';
    /**
     * AdminStatus
     * @enum {integer}
     */
    AdminStatus: 0 | 1 | 2 | 3;
    /**
     * AuditEvent
     * @description What an audit_log row records (ADR-0006).
     * @enum {string}
     */
    AuditEvent: 'created' | 'updated' | 'deleted' | 'logged_in' | 'logged_out' | 'login_failed';
    /** AuditLogResource */
    AuditLogResource: {
      id: number;
      auditable_type: string;
      auditable_id: number | null;
      event: string;
      old_values: {
        [key: string]: unknown;
      } | null;
      new_values: {
        [key: string]: unknown;
      } | null;
      admin_mst_id: number | null;
      actor_user_name: string | null;
      ip_address: string | null;
      /** @description Full timestamp (ISO 8601): the time of day matters in an audit trail */
      created_at: string;
    };
    /** DeleteAdminMstRequest */
    DeleteAdminMstRequest: {
      ids: number[];
    };
    /**
     * Gender
     * @enum {integer}
     */
    Gender: 1 | 2 | 3;
    /**
     * IsActive
     * @enum {integer}
     */
    IsActive: 0 | 1;
    /**
     * IsDelete
     * @enum {integer}
     */
    IsDelete: 0 | 1;
    /** LoginRequest */
    LoginRequest: {
      user_name: string;
      password: string;
    };
    /**
     * StatusEnum
     * @enum {integer}
     */
    StatusEnum: 0 | 1 | 2;
    /** StoreAdminMstRequest */
    StoreAdminMstRequest: {
      /** Format: email */
      email: string;
      user_name: string;
      password: string;
      first_name: string;
      last_name: string;
      address?: string | null;
      phone_number?: string | null;
      birth?: string | null;
      gender: components['schemas']['Gender'];
      status: components['schemas']['AdminStatus'];
      is_active: components['schemas']['IsActive'];
      role?: components['schemas']['AdminRole'];
      avatar?: string | null;
      is_delete: components['schemas']['IsDelete'];
    };
    /** UpdateAdminMstRequest */
    UpdateAdminMstRequest: {
      id: number;
      /** Format: email */
      email: string;
      user_name: string;
      password?: string | null;
      first_name: string;
      last_name: string;
      address?: string | null;
      phone_number?: string | null;
      birth?: string | null;
      gender: components['schemas']['Gender'];
      status: components['schemas']['AdminStatus'];
      is_active: components['schemas']['IsActive'];
      role?: components['schemas']['AdminRole'];
      avatar?: string | null;
      is_delete?: components['schemas']['IsDelete'] | null;
    };
  };
  responses: {
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string;
        };
      };
    };
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string;
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[];
          };
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'adminMst.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        email?: string | null;
        user_name?: string | null;
        first_name?: string | null;
        last_name?: string | null;
        address?: string | null;
        phone_number?: string | null;
        birth?: string | null;
        gender?: components['schemas']['Gender'] | null;
        status?: components['schemas']['StatusEnum'] | null;
        is_active?: components['schemas']['IsActive'] | null;
        role?: components['schemas']['AdminRole'] | null;
        avatar?: string | null;
        is_delete?: components['schemas']['IsDelete'] | null;
        from_date?: string | null;
        to_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `AdminMstResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AdminMstResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': number;
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': number;
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'adminMst.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAdminMstRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'auditLog.list': {
    parameters: {
      query?: {
        id?: number | null;
        page?: number | null;
        per_page?: number | null;
        sort_by?: string | null;
        sort_order?: string | null;
        auditable_type?: string | null;
        auditable_id?: number | null;
        event?: components['schemas']['AuditEvent'] | null;
        admin_mst_id?: number | null;
        from_date?: string | null;
        to_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Array of `AuditLogResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['AuditLogResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'credential.login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown[];
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Error overview. */
            message: string;
          };
        };
      };
    };
  };
  'credential.logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
    };
  };
  'credential.me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown[];
        };
      };
      401: components['responses']['AuthenticationException'];
    };
  };
  'sanctum.csrf-cookie': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description No content
       *
       *     No content
       */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown[];
        };
      };
    };
  };
}
